2025-01-18 14:03:51,885 - Starting system tray application...
2025-01-18 14:03:51,887 - Starting new HTTP connection (1): 107.128.239.126:5000
2025-01-18 14:03:51,899 - http://107.128.239.126:5000 "GET /check_license?hash=c11d25b55c79d4110f204827684b766d85a3910fabe793b4460289ff31f10018&key=6efe1d21-a0c1-4ffd-9a9c-d22776356956 HTTP/1.1" 500 265
2025-01-18 14:04:15,258 - Starting new HTTP connection (1): 107.128.239.126:5000
2025-01-18 14:04:15,269 - http://107.128.239.126:5000 "GET /check_license?hash=c11d25b55c79d4110f204827684b766d85a3910fabe793b4460289ff31f10018&key=6efe1d21-a0c1-4ffd-9a9c-d22776356956 HTTP/1.1" 500 265
2025-01-18 14:04:16,225 - Starting new HTTP connection (1): 107.128.239.126:5000
2025-01-18 14:04:16,231 - http://107.128.239.126:5000 "GET /check_license?hash=c11d25b55c79d4110f204827684b766d85a3910fabe793b4460289ff31f10018&key=6efe1d21-a0c1-4ffd-9a9c-d22776356956 HTTP/1.1" 500 265
2025-01-18 14:04:26,081 - Importing BlpImagePlugin
2025-01-18 14:04:26,083 - Importing BmpImagePlugin
2025-01-18 14:04:26,083 - Importing BufrStubImagePlugin
2025-01-18 14:04:26,083 - Importing CurImagePlugin
2025-01-18 14:04:26,084 - Importing DcxImagePlugin
2025-01-18 14:04:26,085 - Importing DdsImagePlugin
2025-01-18 14:04:26,088 - Importing EpsImagePlugin
2025-01-18 14:04:26,089 - Importing FitsImagePlugin
2025-01-18 14:04:26,091 - Importing FliImagePlugin
2025-01-18 14:04:26,091 - Importing FpxImagePlugin
2025-01-18 14:04:26,092 - Image: failed to import FpxImagePlugin: No module named 'olefile'
2025-01-18 14:04:26,093 - Importing FtexImagePlugin
2025-01-18 14:04:26,093 - Importing GbrImagePlugin
2025-01-18 14:04:26,094 - Importing GifImagePlugin
2025-01-18 14:04:26,094 - Importing GribStubImagePlugin
2025-01-18 14:04:26,094 - Importing Hdf5StubImagePlugin
2025-01-18 14:04:26,095 - Importing IcnsImagePlugin
2025-01-18 14:04:26,096 - Importing IcoImagePlugin
2025-01-18 14:04:26,097 - Importing ImImagePlugin
2025-01-18 14:04:26,098 - Importing ImtImagePlugin
2025-01-18 14:04:26,099 - Importing IptcImagePlugin
2025-01-18 14:04:26,099 - Importing JpegImagePlugin
2025-01-18 14:04:26,099 - Importing Jpeg2KImagePlugin
2025-01-18 14:04:26,099 - Importing McIdasImagePlugin
2025-01-18 14:04:26,100 - Importing MicImagePlugin
2025-01-18 14:04:26,101 - Image: failed to import MicImagePlugin: No module named 'olefile'
2025-01-18 14:04:26,101 - Importing MpegImagePlugin
2025-01-18 14:04:26,102 - Importing MpoImagePlugin
2025-01-18 14:04:26,111 - Importing MspImagePlugin
2025-01-18 14:04:26,112 - Importing PalmImagePlugin
2025-01-18 14:04:26,113 - Importing PcdImagePlugin
2025-01-18 14:04:26,113 - Importing PcxImagePlugin
2025-01-18 14:04:26,113 - Importing PdfImagePlugin
2025-01-18 14:04:26,118 - Importing PixarImagePlugin
2025-01-18 14:04:26,118 - Importing PngImagePlugin
2025-01-18 14:04:26,118 - Importing PpmImagePlugin
2025-01-18 14:04:26,118 - Importing PsdImagePlugin
2025-01-18 14:04:26,119 - Importing QoiImagePlugin
2025-01-18 14:04:26,120 - Importing SgiImagePlugin
2025-01-18 14:04:26,120 - Importing SpiderImagePlugin
2025-01-18 14:04:26,121 - Importing SunImagePlugin
2025-01-18 14:04:26,121 - Importing TgaImagePlugin
2025-01-18 14:04:26,122 - Importing TiffImagePlugin
2025-01-18 14:04:26,122 - Importing WebPImagePlugin
2025-01-18 14:04:26,123 - Importing WmfImagePlugin
2025-01-18 14:04:26,124 - Importing XbmImagePlugin
2025-01-18 14:04:26,125 - Importing XpmImagePlugin
2025-01-18 14:04:26,125 - Importing XVThumbImagePlugin
2025-01-18 14:04:31,302 - Starting new HTTP connection (1): 107.128.239.126:5000
2025-01-18 14:04:31,326 - http://107.128.239.126:5000 "GET /check_license?hash=c11d25b55c79d4110f204827684b766d85a3910fabe793b4460289ff31f10018&key=6efe1d21-a0c1-4ffd-9a9c-d22776356956 HTTP/1.1" 500 265
2025-01-18 14:04:35,242 - An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        uMsg, lambda w, l: 0)(wParam, lParam) or 0)
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
    ~~~~~~~~^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 548, in wrapper0
    return action()
  File "c:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\wrapper\NTiMaintence tester.py", line 184, in start_maintenance
    os.remove(Path(os.getenv("APPDATA")) / "NTi" / ".license_key")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\jtann\\AppData\\Roaming\\NTi\\.license_key'
2025-01-18 14:05:30,733 - Starting new HTTP connection (1): 107.128.239.126:5000
2025-01-18 14:05:30,739 - http://107.128.239.126:5000 "GET /check_license?hash=c11d25b55c79d4110f204827684b766d85a3910fabe793b4460289ff31f10018&key=6efe1d21-a0c1-4ffd-9a9c-d22776356956 HTTP/1.1" 500 265
2025-01-18 14:05:34,529 - An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        uMsg, lambda w, l: 0)(wParam, lParam) or 0)
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
    ~~~~~~~~^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 548, in wrapper0
    return action()
  File "c:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\wrapper\NTiMaintence tester.py", line 184, in start_maintenance
    os.remove(Path(os.getenv("APPDATA")) / "NTi" / ".license_key")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\jtann\\AppData\\Roaming\\NTi\\.license_key'
2025-01-18 14:05:38,261 - An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        uMsg, lambda w, l: 0)(wParam, lParam) or 0)
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
    ~~~~~~~~^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 548, in wrapper0
    return action()
  File "c:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\wrapper\NTiMaintence tester.py", line 214, in change_license
    os.remove(Path(os.getenv("APPDATA")) / "NTi" / ".license_key")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\jtann\\AppData\\Roaming\\NTi\\.license_key'
2025-01-18 14:05:41,866 - An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        uMsg, lambda w, l: 0)(wParam, lParam) or 0)
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
    ~~~~~~~~^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\.venv\Lib\site-packages\pystray\_base.py", line 548, in wrapper0
    return action()
  File "c:\Users\jtann\OneDrive\Documents\tuneup app\tune-up-app\wrapper\NTiMaintence tester.py", line 214, in change_license
    os.remove(Path(os.getenv("APPDATA")) / "NTi" / ".license_key")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\jtann\\AppData\\Roaming\\NTi\\.license_key'
